### ISSUE TITLE
Disable the auth system if a superadmin exists

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/TShock#1064]
Currently, the auth system's functionality is determined by the presence of auth.lck inside the TShock config directory. This has both benefits and drawbacks. If you lose your superadmin password, you can delete auth.lck and make a new account very easily, without needing to use SQL. However, if you never use the auth system and run auth-verify, your server is open to attack via bruteforce.

I think that we should disable the auth system if a superadmin exists in the database. If a superadmin exists, just disable the entire system.

An alternative solution is to disable the auth system automatically after 10 minutes of non-use, and to send a very big scary warning to the console if this happens (warning, your server is open to attack, etc).

**Comment by nicatronTg** [comment]
Looking for feedback @NyxStudios/tshock

**Comment by Strinkor** [comment]
I agree with @nicatronTg, if superadmin user will lose password, he can restore it via Database, so yes, :+1:.

**Comment by Kromara** [comment]
I agree entirely. Security is always a top priority.

**Comment by Patrikkk** [comment]
Yeeeee :tumbs-up:
I agree with first option, disable if there is suepradmin.

**Comment by Kromara** [comment]
I was always a fan of @nicatrontg's big scary messages though. ^_^

**Comment by Strinkor** [comment]
I think, we can improve this concept. After using auth system, somehow disable command, somewhere i saw something like this.

**Comment by Gaegamel** [comment]
How about a separate command line parameter in case someone lost his admin-password? Similar to Teamspeak's 3 "-serverquerypassword=<password>" parameter (people tend to forget the serveradminquery-password).

This could be used in conjunction with your suggestion, disabling the auth-system for non-use. Restarting a server, for the most parts, is done very easily. Most users should have no problem with it, since the server goes offline for 2-5 minutes maximum.

**Comment by nicatronTg** [comment]
@Gaegamel the problem with adding something like a command line parameter is that we make the system unusable for people on shared hosts where modifying the startup parameters is impossible.

**Comment by Gaegamel** [comment]
@nicatronTg i see. Still, you could add it as improvement to ease the process of changing the password for users with dedicated maschines or the ability to change startup parameters. So it wouldn't replace the old system, but be an alternative. Users with shared hosting would still only have the option to use a sql-statement (or sqlite-editor, if I remember right, because it is built on sqlite?) to change their password.

This won't improve much, though, which is sad.

However, if it is possible for you, you could add a feature utilizing files and their filenames. For example, a file named ".resetadminpassword". In case, it resides in a special folder (to be determined), the server could check for its appearance. Optionally, it could contain 1 line reading "password=<password>", which would reset the password of superadmin-account to <password>. If this is a hassle, maybe the filename could also contain the new password, so the check would consist of a regex, checking for "(.resetadminpassword)_\w+" (very primitive example; "_" has been used as arbitrary divider).
This option wouldn't cause problems for users on shared hosts as long as they can create files. the performance would be needed to be kept in mind, since a periodic events draws resources (although not as much). I could imagine a period of 30 seconds or 1 min. Even 5 min.

Or it's a check at startup only, thus aperiodic.

**Comment by tylerjwatson** [comment]
Use n->5 random dictionary words. 

Brute forcing isn't an issue when your key is "seven banana ham pants".

**Comment by nicatronTg** [comment]
Was thinking about doing something like that, but including a dictionary
with TShock = including a dictionary attack with TShock.

**Comment by tylerjwatson** [comment]
That's why you don't have an internal dictionary with tshock.

**Comment by nicatronTg** [comment]
So...a dictionary API or something? Is there something built in? You're
probably more versed with the .NET api than me.

**Comment by hastinbe** [comment]
Here's my take using @nicatronTg's original suggestion. Check db for a superadmin and disables auth if exists. Otherwise enables auth and generates code. Also kicks player if auth attempts exceed MaximumLoginAttempts.

 See hastinbe/TShock@a472ca76026c704f596372d4a0c7df7987d73afe

**Comment by WhiteXZ** [comment]
cc @nicatronTg @tylerjwatson @Ijwu see @hastinbe's commit above.

**Comment by tylerjwatson** [comment]
That's cool. Less disk noise and more awesome.

**Comment by tlworks** [comment]
I believe this was fixed?

**Comment by nicatronTg** [comment]
Definitely not fixed because @hastinbe deleted his repo and his PR was never merged before he deleted the repo.

**Comment by Enerdy** [comment]
Hastinbe's solution was pretty cool though. Might spin something similar and see how it goes.
