### ISSUE TITLE
No warps, no regions defined.

### ISSUE THREAD

**Issue by Creepernoop** [NyxStudios/TShock#1280]
It says this: 
 [Server API] Warning Plugin "TShock" has had an unhandled exception thrown by one of its GamePostInitialize handlers:
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at TShockAPI.TShock.OnPostInit(EventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

Im using TShock 4.3.17.0
Please help. It is ruining my server.

**Comment by tlworks** [comment]
And what exactly are you trying to do? What commands were executed?

**Comment by Creepernoop** [comment]
nothing. i just started the server and showed this

**Comment by tlworks** [comment]
Are you running MySQL or SQLite? Are you sure your DB is running and contains all required tables?

**Comment by tlworks** [comment]
According to `System.OverflowException: Value was either too large or too small for an Int32.` a Value is either too small or too big, which is probably a value defined in your config or your DB.

**Comment by Creepernoop** [comment]
what is mysql and sqlite
oh i will verify the config

**Comment by Creepernoop** [comment]
i have sqlite 3

**Comment by tlworks** [comment]
By default a TShock Terraria Server runs on SQLite database, larger Servers often use MySQL or other supported DB's.

**Comment by Creepernoop** [comment]
oh done. I had MaxHP at 10000 =D

**Comment by WhiteXZ** [comment]
Please delete your authcode.txt

**Comment by Creepernoop** [comment]
now i think it is fixed

**Comment by Creepernoop** [comment]
it isn't fixed

**Comment by tlworks** [comment]
Please consider elaborating on your actions, as posts simply containing 'it isn't fixed' doesn't help neither of us.

**Comment by Creepernoop** [comment]
Oh ok. I must delete a plugin?

**Comment by Zaicon** [comment]
Please try deleting your 'authcode.txt' file and restart the server.

**Comment by Creepernoop** [comment]
Sure.I deleted the auth code. Now the logs are clear and no errors. Thanks a lot.
