### ISSUE TITLE
Server Hangs at Found Server

### ISSUE THREAD

**Issue by Meowwz** [NyxStudios/TShock#1356]
Windows 7 64-bit fully patched. If password is specified server runs but when clients connect Terraria hangs after password is given - just shows "Found Server". Server side just shows "IPAddress:Port is connecting...." Nothing in extended logs. Tried "Run As Administrator" - same result. If no password is specified everything runs fine.
[ServerLog.txt](https://github.com/NyxStudios/TShock/files/668043/ServerLog.txt)

**Comment by Holyverz** [comment]
I have the same problem on Windows server 2016 Standard . No problem when there's no password

**Comment by WhiteXZ** [comment]
From my testing:
* Setting a password via the server prompt results in "Found Server"
* Setting a password in the tshock config (`"ServerPassword": "password"`) is fine
* Doing both results in "Found Server"

**Comment by ProfessorXZ** [comment]
A few things to note about the above statement: I don't see any code referencing the config's ServerPassword field, meaning that setting the password via the config equals to not setting one at all. So the reason why setting the password in both the config and the console results in "Found Server" is that you're doing the same thing.

**Comment by WhiteXZ** [comment]
@professorxz https://github.com/NyxStudios/TShock/blob/general-devel/TShockAPI/GetDataHandlers.cs#L1564

**Comment by Marcus101RR** [comment]
So basically TShock doesn't inherit the vanilla form, and causes it to go ape. Lesson learned for now: Use Tshock method if you are using tshock.

**Comment by ProfessorXZ** [comment]
The leson learned is never use TShock.
@WhiteXZ 👍 The IDE didn't show anything, might've screwed up the search somehow. This issue still makes no sense.

**Comment by WhiteXZ** [comment]
Resolved in 4f7a15f9bf9def857ef9b0ce8c8b46e13fe68af3

**Comment by GNUGradyn** [comment]
Still appears to be a problem, I started a web server on that port to test it, the web port works properly, so its not a firewall issue. Ubuntu server 16.10

**Comment by Marcus101RR** [comment]
If you are using a port that is being used while Terraria tries to obtain it then you will always have a "Found Server" issue. Most cases involved with "Found server" is because the port being used is already in use by another application.

Please do not use a port that is already in use, use another. Config works for me.
